DOWNLOAD_VERSION: 0.8.1
ALERT_CLASS: 
ALERT: 

langs:
  en: English
  fr: Français
  nl: Nederlands
  
section:
  index:
    en: 
    fr: 
    nl:
  about:
    en: about
    fr: a-propos
    nl: over-bitcoin
  bitcoin-for-developers:
    en: bitcoin-for-developers
    fr: bitcoin-pour-developpeurs
    nl: bitcoin-voor-ontwikkelaars
  bitcoin-for-enthusiasts:
    en: bitcoin-for-enthusiasts
    fr: bitcoin-pour-passionnes
    nl: bitcoin-voor-liefhebbers
  bitcoin-for-individuals:
    en: bitcoin-for-individuals
    fr: bitcoin-pour-particuliers
    nl: bitcoin-voor-particulieren
  bitcoin-for-businesses:
    en: bitcoin-for-businesses
    fr: bitcoin-pour-entreprises
    nl: bitcoin-voor-bedrijven
  choose-your-wallet:
    en: choose-your-wallet
    fr: choisir-votre-porte-monnaie
    nl: kies-je-wallet
  community:
    en: community
    fr: communaute
    nl: community
  development:
    en: development
    fr: developpement
    nl: ontwikkeling
  download:
    en: download
    fr: telecharger
    nl: download
  foundation:
    en: foundation
    fr: fondation
    nl: stichting
  how-it-works:
    en: how-it-works
    fr: comment-ca-marche
    nl: hoe-het-werkt
  resources:
    en: resources
    fr: ressources
    nl: hulpmiddelen
  support-bitcoin:
    en: support-bitcoin
    fr: supporter-bitcoin
    nl: help-bitcoin
  version-history:
    en: version-history
  vocabulary:
    en: vocabulary
    fr: vocabulaire
    nl: woordenlijst
  you-need-to-know:
    en: you-need-to-know
    fr: vous-devez-savoir
    nl: wat-u-moet-weten

safe:        false
auto:        false
server:      false
server_port: 4000
base-url:    /

source:      .
destination: ./_site
plugins:     ./_plugins

future:      true
lsi:         false
pygments:    false
markdown:    maruku
permalink:   date

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false
  
  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style
    
aliases:
  s_nakamoto: Satoshi Nakamoto
  --author=Satoshi Nakamoto: Satoshi Nakamoto
  gavinandresen: Gavin Andresen
  tcatm: Nils Schneider
